version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      - exemplo-tier
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
      - 9094:9094
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,PLAINTEXT_DEV://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DEV:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092,PLAINTEXT_DEV://${HOSTNAME_COMMAND}:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_HOST
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - exemplo-tier

  mysql:
    image: mysql:8.0.23
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exemplodb
      MYSQL_ROOT_PASSWORD: exemploapi
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: exemplouser
      MYSQL_PASSWORD: exemplouser
    networks:
      - exemplo-tier

  connect:
    image: debezium/connect:1.4
    container_name: connect
    hostname: connect
    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    networks:
      - exemplo-tier

  exemploapi:
    build:
      context: ../  # Diretório onde o Dockerfile está localizado
      dockerfile: Dockerfile
    container_name: exemploapi
    hostname: exemploapi
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
      - mysql
    restart: always
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql:3306/exemplodb
      DATASOURCE_USERNAME: exemplouser
      DATASOURCE_PASSWORD: exemplouser
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - exemplo-tier

  redpanda-console:
    image: redpandadata/console:v2.3.1
    container_name: redpanda-console
    hostname: redpanda-console
    ports:
      - 8090:8080
    environment:
      KAFKA_BROKERS: kafka:29092
      KAFKA_SCHEMAREGISTRY_ENABLED: "false"
      REDPANDA_ADMINAPI_ENABLED: "false"
    networks:
      - exemplo-tier

networks:
  exemplo-tier:
    driver: bridge
