version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      - exemplo-tier
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:6.1.1
    container_name: kafka
    hostname: kakfa
    ports:
      - 9092:9092
      - 9101:9101
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT2:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT2://kafka:29292,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - exemplo-tier
  mysql:
    image: library/mysql:8.0.23
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=exemplodb
      - MYSQL_ROOT_PASSWORD=exemploapi
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=exemplouser
      - MYSQL_PASSWORD=exemplouser
    networks:
      - exemplo-tier
  connect:
    image: debezium/connect:1.4
    container_name: connect
    hostname: connect
    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - exemplo-tier

  exemploapi:
    image: exemplo-api:latest
    container_name: exemploapi
    hostname: exemploapi
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
      - mysql
    restart: always
    environment:
      - DATASOURCE_URL=jdbc:mysql://mysql:3306/exemplodb
      - DATASOURCE_USERNAME=exemplouser
      - DATASOURCE_PASSWORD=exemplouser
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - exemplo-tier

networks:
  exemplo-tier:
    driver: bridge

